Repository solstice-station-13/solstice-station-13, pull requests merged in 2021-03, with the labels that each got.

#29 Fixes Command Ages
  maps/torch/job/command_jobs.dm
Labels: enhancement

#31 General Chemical Ports
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: enhancement

#32 The Army Goes Rolling Along
  maps/torch/datums/uniforms_army.dm
  maps/torch/items/clothing/solgov-accessory.dm
  maps/torch/job/command_jobs.dm
  maps/torch/job/outfits/security_outfits.dm
  maps/torch/job/security_jobs.dm
  maps/torch/torch.dm
  maps/torch/torch_ranks.dm
Labels: enhancement, stupid idea

#34 Army Implementation Part Two
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/tactical.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  maps/torch/datums/uniforms_army.dm
  maps/torch/items/clothing/solgov-head.dm
  maps/torch/items/clothing/solgov-under.dm
  maps/torch/job/outfits/command_outfits.dm
  maps/torch/job/outfits/security_outfits.dm
  maps/torch/loadout/_defines.dm
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/loadout/loadout_head.dm
  maps/torch/loadout/loadout_suit.dm
  maps/torch/loadout/loadout_uniform.dm
Labels: enhancement, stupid idea

#35 Assorted Army Fixes
  maps/torch/items/clothing/solgov-under.dm
  maps/torch/job/command_jobs.dm
  maps/torch/torch_ranks.dm
Labels: enhancement

#36 Major Update
  code/__defines/culture.dm
  code/__defines/languages.dm
  code/__defines/mobs.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/culture_descriptor/culture/cultures_sergal.dm
  code/modules/culture_descriptor/culture/cultures_taj.dm
  code/modules/culture_descriptor/culture/cultures_vulp.dm
  code/modules/culture_descriptor/faction/factions_taj.dm
  code/modules/culture_descriptor/faction/factions_vulp.dm
  code/modules/culture_descriptor/location/locations_sergal.dm
  code/modules/culture_descriptor/location/locations_taj.dm
  code/modules/culture_descriptor/location/locations_vulp.dm
  code/modules/culture_descriptor/religion/religions_sergal.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/language/alien/sergal.dm
  code/modules/mob/language/alien/solstice.dm
  code/modules/power/lighting.dm
  code/modules/sprite_accessories/_accessory_hair.dm
  code/stylesheet.dm
  icons/atmos/vent_pump.dmi
  icons/atmos/vent_scrubber.dmi
  maps/torch/job/command_jobs.dm
  maps/torch/torch_ranks.dm
  modular_solstice/code/modules/species/station/akula.dm
  modular_solstice/code/modules/species/station/custom.dm
  modular_solstice/code/modules/species/station/sergal.dm
  modular_solstice/code/modules/species/station/tajaran.dm
  modular_solstice/code/modules/species/station/vasilissan.dm
  modular_solstice/code/modules/species/station/vulpkanin.dm
  modular_solstice/icons/mob/human_races/species/sergal/tail.dmi
  modular_solstice/icons/mob/human_races/species/tajaran/tail.dmi
  modular_solstice/icons/mob/human_races/species/vulpkanin/tail.dmi
  solstice-station-13.dme
Labels: enhancement, fucking sergals, stupid idea

#38 Lore Expansion
  code/__defines/culture.dm
  code/__defines/mobs.dm
  code/modules/culture_descriptor/culture/cultures_duroj.dm
  code/modules/culture_descriptor/culture/cultures_human.dm
  code/modules/culture_descriptor/culture/cultures_khazan.dm
  code/modules/culture_descriptor/culture/cultures_sergal.dm
  code/modules/culture_descriptor/culture/cultures_vulp.dm
  code/modules/culture_descriptor/location/locations_duroj.dm
  code/modules/culture_descriptor/location/locations_human.dm
  code/modules/culture_descriptor/location/locations_khazan.dm
  code/modules/culture_descriptor/religion/religions_human.dm
  code/modules/culture_descriptor/religion/religions_khazan.dm
  code/modules/culture_descriptor/religion/religions_taj.dm
  code/modules/mob/language/alien/solstice.dm
  code/modules/species/station/station.dm
  maps/torch/job/command_jobs.dm
  maps/torch/torch_ranks.dm
  modular_solstice/code/modules/species/station/akula.dm
  modular_solstice/code/modules/species/station/custom.dm
  modular_solstice/code/modules/species/station/duroj.dm
  modular_solstice/code/modules/species/station/khazan.dm
  modular_solstice/code/modules/species/station/sergal.dm
  modular_solstice/code/modules/species/station/tajaran.dm
  modular_solstice/code/modules/species/station/vulpkanin.dm
  modular_solstice/icons/mob/human_races/species/duroj/body.dmi
  modular_solstice/icons/mob/human_races/species/duroj/husk.dmi
  modular_solstice/icons/mob/human_races/species/duroj/preview.dmi
  modular_solstice/icons/mob/human_races/species/duroj/tail.dmi
  modular_solstice/icons/mob/human_races/species/khazan/body.dmi
  modular_solstice/icons/mob/human_races/species/khazan/husk.dmi
  modular_solstice/icons/mob/human_races/species/khazan/preview.dmi
  modular_solstice/icons/mob/human_races/species/khazan/tail.dmi
  solstice-station-13.dme
Labels: enhancement, lore
